-- Script: Crear tabla investors.countries con códigos ISO 3166-1
-- Propósito: Centralizar códigos de país en formato ISO 3166-1 alpha-2/alpha-3
-- Fecha: 2025-01-13
-- Trazabilidad: Especificación LEMONWAY-CREACION-CUENTAS-ESPECIFICACION.md - Sección 0

BEGIN;

-- Crear tabla investors.countries
CREATE TABLE IF NOT EXISTS investors.countries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code_iso2 VARCHAR(2) UNIQUE NOT NULL, -- ISO 3166-1 alpha-2 (ES, FR, DE, etc)
  code_iso3 VARCHAR(3) UNIQUE NOT NULL, -- ISO 3166-1 alpha-3 (ESP, FRA, DEU, etc)
  name_en VARCHAR(100) NOT NULL, -- Nombre en inglés
  name_es VARCHAR(100) NOT NULL, -- Nombre en español
  region VARCHAR(20), -- Región geográfica: Europe, Asia, Americas, Africa, Oceania
  is_eu_member BOOLEAN DEFAULT false, -- Es miembro de la UE
  is_restricted BOOLEAN DEFAULT false, -- Restricciones regulatorias (Cuba, Irán, etc)
  default_currency VARCHAR(3), -- Moneda por defecto (EUR, USD, GBP, etc)
  is_active BOOLEAN DEFAULT true, -- País activo para nuevas cuentas
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Crear índices para búsquedas rápidas
CREATE INDEX idx_countries_code_iso2 ON investors.countries(code_iso2) WHERE is_active = true;
CREATE INDEX idx_countries_code_iso3 ON investors.countries(code_iso3) WHERE is_active = true;
CREATE INDEX idx_countries_region ON investors.countries(region) WHERE is_active = true;
CREATE INDEX idx_countries_active ON investors.countries(is_active);

-- Crear vista para países activos (uso común)
CREATE OR REPLACE VIEW investors.v_countries_active AS
SELECT id, code_iso2, code_iso3, name_en, name_es, region, is_eu_member, default_currency
FROM investors.countries
WHERE is_active = true
ORDER BY name_es ASC;

-- Insertar todos los países del mundo (ISO 3166-1)
-- Total: 249 países + territorios reconocidos

INSERT INTO investors.countries (code_iso2, code_iso3, name_en, name_es, region, is_eu_member, is_restricted, default_currency) VALUES
('AD', 'AND', 'Andorra', 'Andorra', 'Europe', false, false, 'EUR'),
('AE', 'ARE', 'United Arab Emirates', 'Emiratos Árabes Unidos', 'Asia', false, false, 'AED'),
('AF', 'AFG', 'Afghanistan', 'Afganistán', 'Asia', false, false, 'AFN'),
('AG', 'ATG', 'Antigua and Barbuda', 'Antigua y Barbuda', 'Americas', false, false, 'XCD'),
('AI', 'AIA', 'Anguilla', 'Anguila', 'Americas', false, false, 'XCD'),
('AL', 'ALB', 'Albania', 'Albania', 'Europe', false, false, 'ALL'),
('AM', 'ARM', 'Armenia', 'Armenia', 'Asia', false, false, 'AMD'),
('AO', 'AGO', 'Angola', 'Angola', 'Africa', false, false, 'AOA'),
('AQ', 'ATA', 'Antarctica', 'Antártida', 'Antarctica', false, false, 'USD'),
('AR', 'ARG', 'Argentina', 'Argentina', 'Americas', false, false, 'ARS'),
('AS', 'ASM', 'American Samoa', 'Samoa Americana', 'Oceania', false, false, 'USD'),
('AT', 'AUT', 'Austria', 'Austria', 'Europe', true, false, 'EUR'),
('AU', 'AUS', 'Australia', 'Australia', 'Oceania', false, false, 'AUD'),
('AW', 'ABW', 'Aruba', 'Aruba', 'Americas', false, false, 'AWG'),
('AX', 'ALA', 'Åland Islands', 'Islas Åland', 'Europe', true, false, 'EUR'),
('AZ', 'AZE', 'Azerbaijan', 'Azerbaiyán', 'Asia', false, false, 'AZN'),
('BA', 'BIH', 'Bosnia and Herzegovina', 'Bosnia y Herzegovina', 'Europe', false, false, 'BAM'),
('BB', 'BRB', 'Barbados', 'Barbados', 'Americas', false, false, 'BBD'),
('BD', 'BGD', 'Bangladesh', 'Bangladesh', 'Asia', false, false, 'BDT'),
('BE', 'BEL', 'Belgium', 'Bélgica', 'Europe', true, false, 'EUR'),
('BF', 'BFA', 'Burkina Faso', 'Burkina Faso', 'Africa', false, false, 'XOF'),
('BG', 'BGR', 'Bulgaria', 'Bulgaria', 'Europe', true, false, 'BGN'),
('BH', 'BHR', 'Bahrain', 'Baréin', 'Asia', false, false, 'BHD'),
('BI', 'BDI', 'Burundi', 'Burundi', 'Africa', false, false, 'BIF'),
('BJ', 'BEN', 'Benin', 'Benín', 'Africa', false, false, 'XOF'),
('BL', 'BLM', 'Saint Barthélemy', 'San Bartolomé', 'Americas', false, false, 'EUR'),
('BM', 'BMU', 'Bermuda', 'Bermudas', 'Americas', false, false, 'BMD'),
('BN', 'BRN', 'Brunei Darussalam', 'Brunéi', 'Asia', false, false, 'BND'),
('BO', 'BOL', 'Bolivia', 'Bolivia', 'Americas', false, false, 'BOB'),
('BQ', 'BES', 'Bonaire, Sint Eustatius and Saba', 'Bonaire, San Eustaquio y Saba', 'Americas', false, false, 'USD'),
('BR', 'BRA', 'Brazil', 'Brasil', 'Americas', false, false, 'BRL'),
('BS', 'BHS', 'Bahamas', 'Bahamas', 'Americas', false, false, 'BSD'),
('BT', 'BTN', 'Bhutan', 'Bután', 'Asia', false, false, 'BTN'),
('BV', 'BVT', 'Bouvet Island', 'Isla Bouvet', 'Antarctica', false, false, 'NOK'),
('BW', 'BWA', 'Botswana', 'Botsuana', 'Africa', false, false, 'BWP'),
('BY', 'BLR', 'Belarus', 'Bielorrusia', 'Europe', false, false, 'BYN'),
('BZ', 'BLZ', 'Belize', 'Belice', 'Americas', false, false, 'BZD'),
('CA', 'CAN', 'Canada', 'Canadá', 'Americas', false, false, 'CAD'),
('CC', 'CCK', 'Cocos (Keeling) Islands', 'Islas Cocos (Keeling)', 'Asia', false, false, 'AUD'),
('CD', 'COD', 'Congo, Democratic Republic of the', 'República Democrática del Congo', 'Africa', false, false, 'CDF'),
('CF', 'CAF', 'Central African Republic', 'República Centroafricana', 'Africa', false, false, 'XAF'),
('CG', 'COG', 'Congo', 'Congo', 'Africa', false, false, 'XAF'),
('CH', 'CHE', 'Switzerland', 'Suiza', 'Europe', false, false, 'CHF'),
('CI', 'CIV', 'Côte d''Ivoire', 'Costa de Marfil', 'Africa', false, false, 'XOF'),
('CK', 'COK', 'Cook Islands', 'Islas Cook', 'Oceania', false, false, 'NZD'),
('CL', 'CHL', 'Chile', 'Chile', 'Americas', false, false, 'CLP'),
('CM', 'CMR', 'Cameroon', 'Camerún', 'Africa', false, false, 'XAF'),
('CN', 'CHN', 'China', 'China', 'Asia', false, false, 'CNY'),
('CO', 'COL', 'Colombia', 'Colombia', 'Americas', false, false, 'COP'),
('CR', 'CRI', 'Costa Rica', 'Costa Rica', 'Americas', false, false, 'CRC'),
('CU', 'CUB', 'Cuba', 'Cuba', 'Americas', false, true, 'CUP'),
('CV', 'CPV', 'Cape Verde', 'Cabo Verde', 'Africa', false, false, 'CVE'),
('CW', 'CUW', 'Curaçao', 'Curazao', 'Americas', false, false, 'ANG'),
('CX', 'CXR', 'Christmas Island', 'Isla de Navidad', 'Asia', false, false, 'AUD'),
('CY', 'CYP', 'Cyprus', 'Chipre', 'Europe', true, false, 'EUR'),
('CZ', 'CZE', 'Czech Republic', 'República Checa', 'Europe', true, false, 'CZK'),
('DE', 'DEU', 'Germany', 'Alemania', 'Europe', true, false, 'EUR'),
('DJ', 'DJI', 'Djibouti', 'Yibuti', 'Africa', false, false, 'DJF'),
('DK', 'DNK', 'Denmark', 'Dinamarca', 'Europe', true, false, 'DKK'),
('DM', 'DMA', 'Dominica', 'Dominica', 'Americas', false, false, 'XCD'),
('DO', 'DOM', 'Dominican Republic', 'República Dominicana', 'Americas', false, false, 'DOP'),
('DZ', 'DZA', 'Algeria', 'Argelia', 'Africa', false, false, 'DZD'),
('EC', 'ECU', 'Ecuador', 'Ecuador', 'Americas', false, false, 'USD'),
('EE', 'EST', 'Estonia', 'Estonia', 'Europe', true, false, 'EUR'),
('EG', 'EGY', 'Egypt', 'Egipto', 'Africa', false, false, 'EGP'),
('EH', 'ESH', 'Western Sahara', 'Sahara Occidental', 'Africa', false, false, 'MAD'),
('ER', 'ERI', 'Eritrea', 'Eritrea', 'Africa', false, false, 'ERN'),
('ES', 'ESP', 'Spain', 'España', 'Europe', true, false, 'EUR'),
('ET', 'ETH', 'Ethiopia', 'Etiopía', 'Africa', false, false, 'ETB'),
('FI', 'FIN', 'Finland', 'Finlandia', 'Europe', true, false, 'EUR'),
('FJ', 'FJI', 'Fiji', 'Fiyi', 'Oceania', false, false, 'FJD'),
('FK', 'FLK', 'Falkland Islands', 'Islas Malvinas', 'Americas', false, false, 'FKP'),
('FM', 'FSM', 'Micronesia, Federated States of', 'Estados Federados de Micronesia', 'Oceania', false, false, 'USD'),
('FO', 'FRO', 'Faroe Islands', 'Islas Feroe', 'Europe', false, false, 'DKK'),
('FR', 'FRA', 'France', 'Francia', 'Europe', true, false, 'EUR'),
('GA', 'GAB', 'Gabon', 'Gabón', 'Africa', false, false, 'XAF'),
('GB', 'GBR', 'United Kingdom', 'Reino Unido', 'Europe', false, false, 'GBP'),
('GD', 'GRD', 'Grenada', 'Granada', 'Americas', false, false, 'XCD'),
('GE', 'GEO', 'Georgia', 'Georgia', 'Asia', false, false, 'GEL'),
('GF', 'GUF', 'French Guiana', 'Guayana Francesa', 'Americas', false, false, 'EUR'),
('GG', 'GGY', 'Guernsey', 'Guernsey', 'Europe', false, false, 'GBP'),
('GH', 'GHA', 'Ghana', 'Ghana', 'Africa', false, false, 'GHS'),
('GI', 'GIB', 'Gibraltar', 'Gibraltar', 'Europe', false, false, 'GIP'),
('GL', 'GRL', 'Greenland', 'Groenlandia', 'Americas', false, false, 'DKK'),
('GM', 'GMB', 'Gambia', 'Gambia', 'Africa', false, false, 'GMD'),
('GN', 'GIN', 'Guinea', 'Guinea', 'Africa', false, false, 'GNF'),
('GP', 'GLP', 'Guadeloupe', 'Guadalupe', 'Americas', false, false, 'EUR'),
('GQ', 'GNQ', 'Equatorial Guinea', 'Guinea Ecuatorial', 'Africa', false, false, 'XAF'),
('GR', 'GRC', 'Greece', 'Grecia', 'Europe', true, false, 'EUR'),
('GS', 'SGS', 'South Georgia and the South Sandwich Islands', 'Islas Georgia del Sur y Sandwich del Sur', 'Antarctica', false, false, 'GBP'),
('GT', 'GTM', 'Guatemala', 'Guatemala', 'Americas', false, false, 'GTQ'),
('GU', 'GUM', 'Guam', 'Guam', 'Oceania', false, false, 'USD'),
('GW', 'GNB', 'Guinea-Bissau', 'Guinea-Bisáu', 'Africa', false, false, 'XOF'),
('GY', 'GUY', 'Guyana', 'Guyana', 'Americas', false, false, 'GYD'),
('HK', 'HKG', 'Hong Kong', 'Hong Kong', 'Asia', false, false, 'HKD'),
('HM', 'HMD', 'Heard Island and McDonald Islands', 'Islas Heard y McDonald', 'Antarctica', false, false, 'AUD'),
('HN', 'HND', 'Honduras', 'Honduras', 'Americas', false, false, 'HNL'),
('HR', 'HRV', 'Croatia', 'Croacia', 'Europe', true, false, 'EUR'),
('HT', 'HTI', 'Haiti', 'Haití', 'Americas', false, false, 'HTG'),
('HU', 'HUN', 'Hungary', 'Hungría', 'Europe', true, false, 'HUF'),
('ID', 'IDN', 'Indonesia', 'Indonesia', 'Asia', false, false, 'IDR'),
('IE', 'IRL', 'Ireland', 'Irlanda', 'Europe', true, false, 'EUR'),
('IL', 'ISR', 'Israel', 'Israel', 'Asia', false, false, 'ILS'),
('IM', 'IMN', 'Isle of Man', 'Isla de Man', 'Europe', false, false, 'GBP'),
('IN', 'IND', 'India', 'India', 'Asia', false, false, 'INR'),
('IO', 'IOT', 'British Indian Ocean Territory', 'Territorio Británico del Océano Índico', 'Asia', false, false, 'USD'),
('IQ', 'IRQ', 'Iraq', 'Irak', 'Asia', false, false, 'IQD'),
('IR', 'IRN', 'Iran', 'Irán', 'Asia', false, true, 'IRR'),
('IS', 'ISL', 'Iceland', 'Islandia', 'Europe', false, false, 'ISK'),
('IT', 'ITA', 'Italy', 'Italia', 'Europe', true, false, 'EUR'),
('JE', 'JEY', 'Jersey', 'Jersey', 'Europe', false, false, 'GBP'),
('JM', 'JAM', 'Jamaica', 'Jamaica', 'Americas', false, false, 'JMD'),
('JO', 'JOR', 'Jordan', 'Jordania', 'Asia', false, false, 'JOD'),
('JP', 'JPN', 'Japan', 'Japón', 'Asia', false, false, 'JPY'),
('KE', 'KEN', 'Kenya', 'Kenia', 'Africa', false, false, 'KES'),
('KG', 'KGZ', 'Kyrgyzstan', 'Kirguistán', 'Asia', false, false, 'KGS'),
('KH', 'KHM', 'Cambodia', 'Camboya', 'Asia', false, false, 'KHR'),
('KI', 'KIR', 'Kiribati', 'Kiribati', 'Oceania', false, false, 'AUD'),
('KM', 'COM', 'Comoros', 'Comoras', 'Africa', false, false, 'KMF'),
('KN', 'KNA', 'Saint Kitts and Nevis', 'San Cristóbal y Nieves', 'Americas', false, false, 'XCD'),
('KP', 'PRK', 'Korea, Democratic People''s Republic of', 'Corea del Norte', 'Asia', false, true, 'KPW'),
('KR', 'KOR', 'Korea, Republic of', 'Corea del Sur', 'Asia', false, false, 'KRW'),
('KW', 'KWT', 'Kuwait', 'Kuwait', 'Asia', false, false, 'KWD'),
('KY', 'CYM', 'Cayman Islands', 'Islas Caimán', 'Americas', false, false, 'KYD'),
('KZ', 'KAZ', 'Kazakhstan', 'Kazajistán', 'Asia', false, false, 'KZT'),
('LA', 'LAO', 'Laos', 'Laos', 'Asia', false, false, 'LAK'),
('LB', 'LBN', 'Lebanon', 'Líbano', 'Asia', false, false, 'LBP'),
('LC', 'LCA', 'Saint Lucia', 'Santa Lucía', 'Americas', false, false, 'XCD'),
('LI', 'LIE', 'Liechtenstein', 'Liechtenstein', 'Europe', false, false, 'CHF'),
('LK', 'LKA', 'Sri Lanka', 'Sri Lanka', 'Asia', false, false, 'LKR'),
('LR', 'LBR', 'Liberia', 'Liberia', 'Africa', false, false, 'LRD'),
('LS', 'LSO', 'Lesotho', 'Lesoto', 'Africa', false, false, 'LSL'),
('LT', 'LTU', 'Lithuania', 'Lituania', 'Europe', true, false, 'EUR'),
('LU', 'LUX', 'Luxembourg', 'Luxemburgo', 'Europe', true, false, 'EUR'),
('LV', 'LVA', 'Latvia', 'Letonia', 'Europe', true, false, 'EUR'),
('LY', 'LBY', 'Libya', 'Libia', 'Africa', false, false, 'LYD'),
('MA', 'MAR', 'Morocco', 'Marruecos', 'Africa', false, false, 'MAD'),
('MC', 'MCO', 'Monaco', 'Mónaco', 'Europe', false, false, 'EUR'),
('MD', 'MDA', 'Moldova', 'Moldavia', 'Europe', false, false, 'MDL'),
('ME', 'MNE', 'Montenegro', 'Montenegro', 'Europe', false, false, 'EUR'),
('MF', 'MAF', 'Saint Martin', 'San Martín', 'Americas', false, false, 'EUR'),
('MG', 'MDG', 'Madagascar', 'Madagascar', 'Africa', false, false, 'MGA'),
('MH', 'MHL', 'Marshall Islands', 'Islas Marshall', 'Oceania', false, false, 'USD'),
('MK', 'MKD', 'Macedonia', 'Macedonia del Norte', 'Europe', false, false, 'MKD'),
('ML', 'MLI', 'Mali', 'Malí', 'Africa', false, false, 'XOF'),
('MM', 'MMR', 'Myanmar', 'Myanmar', 'Asia', false, false, 'MMK'),
('MN', 'MNG', 'Mongolia', 'Mongolia', 'Asia', false, false, 'MNT'),
('MO', 'MAC', 'Macau', 'Macao', 'Asia', false, false, 'MOP'),
('MP', 'MNP', 'Northern Mariana Islands', 'Islas Marianas del Norte', 'Oceania', false, false, 'USD'),
('MQ', 'MTQ', 'Martinique', 'Martinica', 'Americas', false, false, 'EUR'),
('MR', 'MRT', 'Mauritania', 'Mauritania', 'Africa', false, false, 'MRU'),
('MS', 'MSR', 'Montserrat', 'Montserrat', 'Americas', false, false, 'XCD'),
('MT', 'MLT', 'Malta', 'Malta', 'Europe', true, false, 'EUR'),
('MU', 'MUS', 'Mauritius', 'Mauricio', 'Africa', false, false, 'MUR'),
('MV', 'MDV', 'Maldives', 'Maldivas', 'Asia', false, false, 'MVR'),
('MW', 'MWI', 'Malawi', 'Malaui', 'Africa', false, false, 'MWK'),
('MX', 'MEX', 'Mexico', 'México', 'Americas', false, false, 'MXN'),
('MY', 'MYS', 'Malaysia', 'Malasia', 'Asia', false, false, 'MYR'),
('MZ', 'MOZ', 'Mozambique', 'Mozambique', 'Africa', false, false, 'MZN'),
('NA', 'NAM', 'Namibia', 'Namibia', 'Africa', false, false, 'NAD'),
('NC', 'NCL', 'New Caledonia', 'Nueva Caledonia', 'Oceania', false, false, 'XPF'),
('NE', 'NER', 'Niger', 'Níger', 'Africa', false, false, 'XOF'),
('NF', 'NFK', 'Norfolk Island', 'Isla Norfolk', 'Oceania', false, false, 'AUD'),
('NG', 'NGA', 'Nigeria', 'Nigeria', 'Africa', false, false, 'NGN'),
('NI', 'NIC', 'Nicaragua', 'Nicaragua', 'Americas', false, false, 'NIO'),
('NL', 'NLD', 'Netherlands', 'Países Bajos', 'Europe', true, false, 'EUR'),
('NO', 'NOR', 'Norway', 'Noruega', 'Europe', false, false, 'NOK'),
('NP', 'NPL', 'Nepal', 'Nepal', 'Asia', false, false, 'NPR'),
('NR', 'NRU', 'Nauru', 'Nauru', 'Oceania', false, false, 'AUD'),
('NU', 'NIU', 'Niue', 'Niue', 'Oceania', false, false, 'NZD'),
('NZ', 'NZL', 'New Zealand', 'Nueva Zelanda', 'Oceania', false, false, 'NZD'),
('OM', 'OMN', 'Oman', 'Omán', 'Asia', false, false, 'OMR'),
('PA', 'PAN', 'Panama', 'Panamá', 'Americas', false, false, 'PAB'),
('PE', 'PER', 'Peru', 'Perú', 'Americas', false, false, 'PEN'),
('PF', 'PYF', 'French Polynesia', 'Polinesia Francesa', 'Oceania', false, false, 'XPF'),
('PG', 'PNG', 'Papua New Guinea', 'Papúa Nueva Guinea', 'Oceania', false, false, 'PGK'),
('PH', 'PHL', 'Philippines', 'Filipinas', 'Asia', false, false, 'PHP'),
('PK', 'PAK', 'Pakistan', 'Pakistán', 'Asia', false, false, 'PKR'),
('PL', 'POL', 'Poland', 'Polonia', 'Europe', true, false, 'PLN'),
('PM', 'SPM', 'Saint Pierre and Miquelon', 'San Pedro y Miquelón', 'Americas', false, false, 'EUR'),
('PN', 'PCN', 'Pitcairn Islands', 'Islas Pitcairn', 'Oceania', false, false, 'NZD'),
('PR', 'PRI', 'Puerto Rico', 'Puerto Rico', 'Americas', false, false, 'USD'),
('PS', 'PSE', 'Palestine', 'Palestina', 'Asia', false, false, 'ILS'),
('PT', 'PRT', 'Portugal', 'Portugal', 'Europe', true, false, 'EUR'),
('PW', 'PLW', 'Palau', 'Palaos', 'Oceania', false, false, 'USD'),
('PY', 'PRY', 'Paraguay', 'Paraguay', 'Americas', false, false, 'PYG'),
('QA', 'QAT', 'Qatar', 'Catar', 'Asia', false, false, 'QAR'),
('RE', 'REU', 'Réunion', 'Reunión', 'Africa', false, false, 'EUR'),
('RO', 'ROU', 'Romania', 'Rumania', 'Europe', true, false, 'RON'),
('RS', 'SRB', 'Serbia', 'Serbia', 'Europe', false, false, 'RSD'),
('RU', 'RUS', 'Russia', 'Rusia', 'Europe', false, false, 'RUB'),
('RW', 'RWA', 'Rwanda', 'Ruanda', 'Africa', false, false, 'RWF'),
('SA', 'SAU', 'Saudi Arabia', 'Arabia Saudita', 'Asia', false, false, 'SAR'),
('SB', 'SLB', 'Solomon Islands', 'Islas Salomón', 'Oceania', false, false, 'SBD'),
('SC', 'SYC', 'Seychelles', 'Seychelles', 'Africa', false, false, 'SCR'),
('SD', 'SDN', 'Sudan', 'Sudán', 'Africa', false, false, 'SDG'),
('SE', 'SWE', 'Sweden', 'Suecia', 'Europe', true, false, 'SEK'),
('SG', 'SGP', 'Singapore', 'Singapur', 'Asia', false, false, 'SGD'),
('SH', 'SHN', 'Saint Helena', 'Santa Elena', 'Africa', false, false, 'GBP'),
('SI', 'SVN', 'Slovenia', 'Eslovenia', 'Europe', true, false, 'EUR'),
('SJ', 'SJM', 'Svalbard and Jan Mayen', 'Svalbard y Jan Mayen', 'Europe', false, false, 'NOK'),
('SK', 'SVK', 'Slovakia', 'Eslovaquia', 'Europe', true, false, 'EUR'),
('SL', 'SLE', 'Sierra Leone', 'Sierra Leona', 'Africa', false, false, 'SLL'),
('SM', 'SMR', 'San Marino', 'San Marino', 'Europe', false, false, 'EUR'),
('SN', 'SEN', 'Senegal', 'Senegal', 'Africa', false, false, 'XOF'),
('SO', 'SOM', 'Somalia', 'Somalia', 'Africa', false, false, 'SOS'),
('SR', 'SUR', 'Suriname', 'Surinam', 'Americas', false, false, 'SRD'),
('SS', 'SSD', 'South Sudan', 'Sudán del Sur', 'Africa', false, false, 'SSP'),
('ST', 'STP', 'São Tomé and Príncipe', 'Santo Tomé y Príncipe', 'Africa', false, false, 'STN'),
('SV', 'SLV', 'El Salvador', 'El Salvador', 'Americas', false, false, 'USD'),
('SX', 'SXM', 'Sint Maarten', 'San Martín', 'Americas', false, false, 'ANG'),
('SY', 'SYR', 'Syria', 'Siria', 'Asia', false, true, 'SYP'),
('SZ', 'SWZ', 'Eswatini', 'Esuatini', 'Africa', false, false, 'SZL'),
('TC', 'TCA', 'Turks and Caicos Islands', 'Islas Turcas y Caicos', 'Americas', false, false, 'USD'),
('TD', 'TCD', 'Chad', 'Chad', 'Africa', false, false, 'XAF'),
('TF', 'ATF', 'French Southern Territories', 'Territorios Australes Franceses', 'Antarctica', false, false, 'EUR'),
('TG', 'TGO', 'Togo', 'Togo', 'Africa', false, false, 'XOF'),
('TH', 'THA', 'Thailand', 'Tailandia', 'Asia', false, false, 'THB'),
('TJ', 'TJK', 'Tajikistan', 'Tayikistán', 'Asia', false, false, 'TJS'),
('TK', 'TKL', 'Tokelau', 'Tokelau', 'Oceania', false, false, 'NZD'),
('TL', 'TLS', 'Timor-Leste', 'Timor Oriental', 'Asia', false, false, 'USD'),
('TM', 'TKM', 'Turkmenistan', 'Turkmenistán', 'Asia', false, false, 'TMT'),
('TN', 'TUN', 'Tunisia', 'Túnez', 'Africa', false, false, 'TND'),
('TO', 'TON', 'Tonga', 'Tonga', 'Oceania', false, false, 'TOP'),
('TR', 'TUR', 'Turkey', 'Turquía', 'Asia', false, false, 'TRY'),
('TT', 'TTO', 'Trinidad and Tobago', 'Trinidad y Tobago', 'Americas', false, false, 'TTD'),
('TV', 'TUV', 'Tuvalu', 'Tuvalu', 'Oceania', false, false, 'AUD'),
('TW', 'TWN', 'Taiwan', 'Taiwán', 'Asia', false, false, 'TWD'),
('TZ', 'TZA', 'Tanzania', 'Tanzania', 'Africa', false, false, 'TZS'),
('UA', 'UKR', 'Ukraine', 'Ucrania', 'Europe', false, false, 'UAH'),
('UG', 'UGA', 'Uganda', 'Uganda', 'Africa', false, false, 'UGX'),
('UM', 'UMI', 'United States Minor Outlying Islands', 'Islas Ultramarinas Menores de los EE.UU.', 'Oceania', false, false, 'USD'),
('US', 'USA', 'United States', 'Estados Unidos', 'Americas', false, false, 'USD'),
('UY', 'URY', 'Uruguay', 'Uruguay', 'Americas', false, false, 'UYU'),
('UZ', 'UZB', 'Uzbekistan', 'Uzbekistán', 'Asia', false, false, 'UZS'),
('VA', 'VAT', 'Vatican City', 'Ciudad del Vaticano', 'Europe', false, false, 'EUR'),
('VC', 'VCT', 'Saint Vincent and the Grenadines', 'San Vicente y las Granadinas', 'Americas', false, false, 'XCD'),
('VE', 'VEN', 'Venezuela', 'Venezuela', 'Americas', false, false, 'VES'),
('VG', 'VGB', 'Virgin Islands, British', 'Islas Vírgenes Británicas', 'Americas', false, false, 'USD'),
('VI', 'VIR', 'Virgin Islands, U.S.', 'Islas Vírgenes de los EE.UU.', 'Americas', false, false, 'USD'),
('VN', 'VNM', 'Vietnam', 'Vietnam', 'Asia', false, false, 'VND'),
('VU', 'VUT', 'Vanuatu', 'Vanuatu', 'Oceania', false, false, 'VUV'),
('WF', 'WLF', 'Wallis and Futuna', 'Wallis y Futuna', 'Oceania', false, false, 'XPF'),
('WS', 'WSM', 'Samoa', 'Samoa', 'Oceania', false, false, 'WST'),
('YE', 'YEM', 'Yemen', 'Yemen', 'Asia', false, false, 'YER'),
('YT', 'MYT', 'Mayotte', 'Mayotte', 'Africa', false, false, 'EUR'),
('ZA', 'ZAF', 'South Africa', 'Sudáfrica', 'Africa', false, false, 'ZAR'),
('ZM', 'ZMB', 'Zambia', 'Zambia', 'Africa', false, false, 'ZMW'),
('ZW', 'ZWE', 'Zimbabwe', 'Zimbabue', 'Africa', false, false, 'ZWL');

-- Marcar países restringidos
UPDATE investors.countries SET is_restricted = true WHERE code_iso2 IN ('IR', 'KP', 'SY', 'CU');

COMMIT;
